inc/widgets.php

Added link target option to circle icon widget

---

inc/template-tags.php

Display leave a comment only if comments are open

---

inc/widgets.php
less/widgets.less
style.css

Implemented enhancement #10 
Added email option. Checked if input was email-id and prepended with `mailto:` if necessary.
Added phone option. Checked if input was not a url and prepended with `tel:` if necessary.
Moved RSS link above email and phone options.
Checked if skype link has `skype:` or `callto:` and added if not present.

Social widget update

---

js/jquery.theme-main.js

Added fitvid support for WooCommerce pages

---

content-page.php
content-single.php
content.php
inc/settings.php
inc/template-tags.php

Implemented enhancement #16 
Added page setting  to display featured image in pages. ( This setting will only show on pages. Thanks for the help with that one Greg :) )
Implemented above in `content-page.php`.
Added a new function `vantage_entry_thumbnail() ` in `template-tags.php`. Applied the same to single posts and archive pages. @gregpriday let me know if this is ok.
@Misplon please let me know if any margin/padding changes are needed. I have designed it to look similar to single posts. :)

Page featured image

---

inc/widgets.php
js/color-picker.js

Implemented enhancement #15 and #14 
Changed the existing color field to color picker.
Added color fields for title and text

Icon circle widget colors

---

loops/loop-carousel.php
loops/loop-grid.php
loops/loop-slider.php

Fixed bug #4 
Added condition to check for attachment post type to `loop-grid`, `loop-slider` and `loop-carousel`.

Added attachment compatibility to post widget loops

---

content-single.php

Removed categories from Jetpack Testimonial posts

---

less/widgets.less
style.css

Implemented enhancement #55 
Added styling to the plugin in the msathead. It looks fine in the sidebar and footer.
@Misplon let me know if this wasn't what you had in mind. ;)

Polylang styling

---

inc/customizer.php

Added font size settings for site title and support text

---

functions.php
inc/template-tags.php

Replaced jetpack's site-logo with WP's custom-logo

---

inc/widgets.php

Added icon color option to icon widget

---

inc/customizer.php

Added footer background image layout setting

---

inc/customizer.php

Implement enhancement #64
@Misplon everything working as expected?

Applied footer heading color to all heading elements

---

inc/settings.php

Changed menu collapse setting to range.

---

content.php

Fix page title setting for archive posts

---

js/jquery.theme-main.js

add Tableau to fitVid's ignore list

---

inc/settings.php
inc/template-tags.php
style.css
style.less

Implemented enhancement #82 
Added option to add author comment label
Implemented option in template
Added simple styling

Added option to add post author's comment's label

---

less/widgets.less
style.css

fixed full width stretched issue

---

inc/template-tags.php
style.css
style.less

Implemented enhancement #26 
removed link around comment metadata
increased size of comment form's submit button 
https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fsotest.wpengine.com%2F%3Fp%3D88
Note: this may need review from time to time as the theme evolves :(

Small modifications to improve mobile UX

---

inc/menu.php

fixed issue with menu home icon

---

inc/customizer.php

Added color settings for site title and header text

---

inc/customizer.php

Added setting for menu item horizontal padding

---

style.css
style.less

Set default font families for heading tags

---

inc/settings.php

Changed responsive to Mobile for a few labels

---

inc/customizer.php
style.css
style.less

Fixed issue #95 
@Misplon I have not added any hover styling. Please let me know if it's needed. Thanks.

fixed logo in menu for .site-title

---

functions.php
inc/extras.php
js/jquery.theme-main.js

Implemented  Enhancement #131 
Added class `so-vantage-customizer-preview` to body when in customizer.
Scroll to top was not functioning when **Mobile Navigation** was checked and  **Display Scroll To Top** was unchecked. Fixed it. :)

Customizer preview

---

inc/template-tags.php

Post meta fix

---

inc/settings.php

Added sanitize_callback to the author comment label setting

---

content-single.php

Added link to edit user bio in the author box

---

inc/customizer.php

Added font setting for main navigation

---

js/jquery.theme-main.js
less/widgets.less
style.css

Footer menu styling

---

style.css
style.less

Fixed bug #120 
Please let me know if there is any situation it does not work.

Changed first letter of byline to uppercase

---

less/loops.less
style.css

Excerpt overflow

---

style.css
style.less

Added z-index to .main-navigation

---

style.css
style.less

Implemented enhancement #155 
@AlexGStapleton can you confirm that this sorts out the issue. Thanks.

Used font-weight 700 as a fallback for bold elements.

---

less/page-settings.less
less/widgets.less
style.css

Implemented enhancement #191 
Fixed issue for **Full Width** and **Full Width, With Sidebar** options.

Fullwidth page layout compatibility with boxed layout

---

inc/menu.php
inc/mobilenav/js/mobilenav.js
inc/mobilenav/mobilenav.php
inc/settings.php
inc/template-tags.php
parts/menu.php
style.css
style.less

Added settings for **Mobile Menu**, **Mobile Menu Close**, **Search** and **Menu Home Icon**.
Implemented the settings.
Added a little styling.

Icon settings

---

content-gallery.php
content-image.php
content-video.php
less/slider.less
style.css

Fixed gallery images.
Minor fixes to archive output

Fixes for Post Formats

---

less/widgets.less
style.css

Fixed styling for layout builder and row

---

content-gallery.php
content-image.php
content-single.php
content-video.php
inc/template-tags.php

Fixed error with $post in author box

---

js/jquery.theme-main.js

Implemented enhancement #220 
@Misplon please test. thanks

closing search bar with escape button

---

functions.php

Fixed bug #236 
@Misplon please test. Thanks

Slider now works on blog page

---

style.css
style.less

Fixed responsiveness of custom logo

---

functions.php

Fixed slider on front page

---

inc/mobilenav/css/mobilenav.css
inc/mobilenav/js/mobilenav.js

Fixed bug #223 
please test. Thanks

show dropdown after empty link is clicked

---

js/jquery.theme-main.js
style.css
style.less

Fixed bug #136 
@Misplon please test. Thanks

Added keyboard accessibility for main  menu

---

inc/template-tags.php

Checking if post content has any images

---

inc/widgets.php

This is a follow up to #261 - I didn't spot this previously. 🤦‍♂️

Loop carousel: adjust overlay class in ajax output

---

inc/customizer/google-fonts.php

Vantage Customizer Fonts - Add Catamaran support

---

js/jquery.theme-main.js
style.css
style.less

This PR resolves #234.
There are a few places that need minor formatting adjustments and I'll make a commit for that once @Misplon has had a look.

Sticky Menu Update

---

inc/customizer/customizer.php

This is a fixed version of #281

Customizer setting callbacks: Allow setting to be set to 0

---

inc/panels.php

Resolves #286
Tested using PHP 5.3.

Legacy Theme Styles: Account for Custom Home Page

---

content.php
functions.php
inc/settings.php
inc/template-tags.php

Adds a new option to the archive featured image setting to allow the removal of the archive featured image.

Archive featured img setting

---

searchform.php

This PR will allow screen readers to correctly associate the label with the search form.

Search Form: Add id to search form

---

inc/mobilenav/js/mobilenav.js

Mobile Menu - Add Support for Non-Standard Menu Items Added via Plugins

---

inc/customizer.php
inc/settings.php
parts/masthead.php
parts/menu.php
style.css
style.less

Resolves #294. Adds a default disabled setting to add the site description.
Please, test both masthead layouts. Responsive views and related size and text color settings.

Added site description setting

---

header.php
less/accessibility.less
style.css
style.less

Soon to be a requirement. Added a skip to toolbar/content link.

Added a skip link

---

inc/settings.php
search.php

Resolves https://github.com/siteorigin/vantage/issues/289.
search.php will have a `if ( have_posts() ) :` followed by another `if ( have_posts() ) :` in whatever loop file is used. If you can think of a cleaner way to do that, let me know. Thanks!

Added a search results layout setting

---

inc/customizer.php

Resolves https://github.com/siteorigin/vantage/issues/317.

Added a site tagline color setting

---

css/woocommerce.css
less/css/woocommerce.less

Resolves https://github.com/siteorigin/vantage/issues/319.

Removed duplicate main container padding

---

inc/mobilenav/js/mobilenav.js

Pass Menu Item Classes to Mobile Menu items

---

js/jquery.theme-main.js
rtl.css
rtl.less
style.css
style.less

Resolves https://github.com/siteorigin/vantage/issues/337.
@AlexGStapleton could it be this easy? Test in RTL too, please.

Switch logo in menu spacing to flex

---

functions.php
js/selectivizr.js

File will be minified in the build process. Resolves https://github.com/siteorigin/vantage-premium/issues/8.

Updated selectivizr to v1.0.3b

---

functions.php

Resolves https://github.com/siteorigin/vantage/issues/145.

Don’t output slider codes if plugin not active

---

functions.php

Resolves https://github.com/siteorigin/vantage/issues/342.
I'm not sure why the condition was set so broadly, any ideas Alex? Please, test, can you see an issue with this change?

Only output the home demo slider if demo is set

---

parts/masthead-logo-in-menu.php
style.css
style.less

Resolves https://github.com/siteorigin/vantage/issues/347.
@AlexGStapleton Is there anything this will break that I'm missing?

Align logo in menu logo and site title

---

loops/loop-blog.php
loops/loop-circleicon.php
loops/loop-grid.php

Resolves https://github.com/siteorigin/vantage/issues/354.

Added no-results template to grid and circle icon loops

---

style.css
style.less

Prevent Block Editor full-widths with sidebar

---

css/woocommerce.css
less/css/woocommerce.less

Resolves https://github.com/siteorigin/vantage/issues/369.
@AlexGStapleton I'm not sure why we have padding on a hover state. Can you think of which other buttons we need to test?

Removed hover state padding

---

build-config.js

Related https://github.com/siteorigin/settings/commit/8e55e505f840d0ddea64e7ed398196ccb88940d7

Update build config to include chosen in minify

---

inc/customizer/js/admin.js
inc/customizer/js/live-customizer.js
inc/mobilenav/js/mobilenav.js
inc/sliders/js/sliders.js
js/jquery.flexslider.js
js/jquery.theme-main.js
js/keyboard-image-navigation.js

This will resolve jQuery Migrate Notices.
Demo slider uses the updated Flexslider.

jQuery 3.5 Changes

---

less/slider.less
style.css

This PR will restore the missing slider caption styling.

Flexslider Caption CSS

---

inc/breadcrumbs.php
readme.txt

Based on https://github.com/siteorigin/siteorigin-corp/pull/144

Add rank math breadcrumbs

---

inc/settings.php
inc/template-tags.php

Resolve https://github.com/siteorigin/vantage/issues/373
I added the colon to the $prefix rather than hard coding it to allow for it to be removed in translations.

Add "Blog Archive Title Prefix" Setting

---

css/woocommerce.css
less/css/woocommerce.less

Allows for double-digit quantities without the second digit being hidden.

Increased the cart qty field width

---

functions.php
inc/deprecated.php
inc/extras.php

* To comply with theme guidelines `wp_title` can’t be used.

Deprecated vantage_wp_title

---

inc/customizer.php

Settings to test:
Logo in Menu: Site Title Font
Content Color: Search results page

Customizer Settings Fixes

---

inc/customizer.php

Resolves https://github.com/siteorigin/vantage/issues/406.

Added WooCommerce product title to the Page Title Color setting

---

less/widgets.less
style.css

A re-work of https://github.com/siteorigin/vantage/pull/419.

Reset Vantage values for stretched padded
