- inc/customizer.php
Implemented enhancement #65 
Added option to remove link underline and add link underline on hover.
Applied settings to `.entry-content a` and `.textwidget a`.
> Add link underline and link hover underline option

- functions.php
Implemented enhancement #172 
Note: This does not seem to work for `[embed]` shortcode. I tested it using [WP Canvas - Shortcodes ](https://wordpress.org/plugins/wc-shortcodes/)
> Allowing use of shortcodes in taxonomy descriptions	

- functions.php
[Slack Reference](https://siteorigin.slack.com/archives/themes/p1478591775000265)
With $slider_stretch being set to the default when vantage_metaslider_slider_stretch is empty (which is the case when not enabled), it's impossible to have a regular non-stretched page if the homepage is stretched.
> Remove $slider_stretch default

- css/woocommerce.css
- less/css/woocommerce.less
- sidebar-shop.php
Previously, the no sidebar page layouts still output the sidebar on the shop / product archive.
> Add shop sidebar page layout support

- functions.php
- inc/extras.php
Resolves structured data issue in core. See https://core.trac.wordpress.org/ticket/28482
To summarize, hentry shouldn't be present on pages as it will never have the data it'ss required to have. This core issue won't be resolved due to backwards compatibility concerns.
Related to #204.
> filter hentry from post_class() to resolve core issue

- style.less
Prevent iOS Safari from overriding the colors for phone numbers while still retaining the auto link functionality. A meta tag wouldn't allow this.
https://developer.apple.com/library/content/featuredarticles/iPhoneURLScheme_Reference/PhoneLinks/PhoneLinks.html
> iOS Safari: resolve color issue for phone numbers

- less/widgets.less
- style.css
Currently, the default layout won't look 100% as intended due to SiteOrigin Page Builder 2.5 row class changes. This PR fixes this and maintains compatibility with older versions of PB.
> Add wide-grey support for PB 2.5

- js/jquery.theme-main.js
Fixed bug #237 
iOS does not support `focus()` the way other devices do. Please check to see if this fix causes problems on any device. Thanks
> Fixed search focus bug on iOS devices

- style.css
- style.less
[Reported here](https://siteorigin.com/thread/post-navigation-buttons-get-cut-off-on-mobile/)
This PR will allow for the page navigation to wrap on mobile devices. This helps prevent the navigation from getting cut off when the post names are slightly larger.
(image sourced from the above linked thread)
> Page Navigation Wrap: Allow for text to wrap on mobile

- less/loops.less
- loops/loop-carousel.php
A user has reported issues due to `.overlay` being used. This PR will rename the overlay class to `.vantage-overlay`
> Loop carousel: Rename overlay to prevent conflicts

- less/loops.less
- style.css
This PR will ensure no margin is applied to the slider loop list items. Currently,  the default list styling (which is applied to `.entry-content ul li`) is.
> Loops: Fix slider alignment

- inc/mobilenav/js/mobilenav.js
This PR will allow for hash links with ids defined (#example) to close the mobile menu. Without this PR, the mobile menu will remain open and the user will have to close the mobile menu to see the scrolled location.
> Mobile Menu: Allow for fragment links with ids defined

- functions.php
Currently the multilingual homepage sliders are not supported but with a small modification, they can be.
Related topic on WordPress.org: https://wordpress.org/support/topic/multilingual-home-page-slider/#post-10551461
(Hopefully this will go through fine.)
> Multilingual home page slider support

- inc/sliders.php
Hi,
I work on MetaSlider and had some issues with loading both versions of FlexSlider. This PR forces a choice when the MetaSlider's version is in the queue. Better to prefer my version as it has a few extra PRs that FlexSlider hasn't merged in (yet).
On another note, if you have any future issues with MetaSlider please tag my username and I will address them personally. Or if you have any ideas for better integration, etc I'm happy to discuss it. 
By the way, we are releasing a theming system "soon-ish" so maybe we can add in some Vantage-specific themes to really make the slideshows fit perfectly for your users.
> Dequeue flexslider when metaslider loads it

- js/jquery.theme-main.js
- style.css
- style.less
[Thread](https://siteorigin.com/thread/vantage-update-version-1-7-14-max-mega-menu-no-longer-sticky/)
The width calculation is required due how max mega menu works when boxed. :/
If you would rather avoid it, we could implement [this Max Mega Menu fix](https://www.megamenu.com/documentation/vantage/) but it would result in a design difference to any site that doesn't already have it so it's not something we should really do.
> Fix Mega Menu sticky menu not working

- inc/customizer/customizer.php
Resolve #277.
This is happening due to how customizer setting callbacks work Basically, the callback doesn't use the default value until after saving and this is an issue as the callback multiplies the value which is why it results in 0.
https://github.com/siteorigin/vantage/blob/1.7.14/inc/customizer.php#L729
While this issue could be fixed in the callback itself, it's quite possible other settings are also affected by this sort of issue and this PR will prevent this sort of issue.
> Customizer setting callbacks: Account for empty values by using default value

- inc/customizer/customizer.php
This is a follow up to #278. This will allow users to set the `Site Title Font Size` to `0` for those who want the site title to be restored to how it was pre #278 . This isn't the ideal way to do this but certain people like how this looks and completely removing the output of the site title will change how this looks.
> Customizer setting callbacks: Allow setting to be set to 0

- inc/customizer.php
- inc/customizer/customizer.php
Reverts changes made by #278 to fix #277. Use default value for site title if input value is empty.
An alternative, more general fix is to pass the default value to `get_theme_mod` [here](https://github.com/siteorigin/vantage/blob/4bffb2c88102ea445436ff9a4a9b07b57697d526/inc/customizer/customizer.php#L559) and then remove the condition below it so the callback is called. I didn't do this because it seems like the intention was for callbacks to handle empty values and apply defaults it desired.
> Use default value for Site Title Font Size customizer setting.

- inc/extras.php
- inc/widgets.php
- less/widgets.less
- loops/loop-circleicon.php
- loops/loop-grid.php
- style.css
@AlexGStapleton Please, take a look mate. The goal is to remove the featured image from the Circle Icon post loop when the Customizer setting is none (Customize > Theme Settings > Blog > Featured Image Type: None). There should be no impact if the Featured Image Type is set to Small or Large and there shouldn't be any impact to the regular usage of the Circle Icon widget not in a post loop. Please, note that you'll need to test:
Circle Icon as a widget.
Circle Icon as the selected post loop for the blog.
Circle Icon as the template chosen within a Post Loop widget.
> Remove circle icon loop featured image if false

- inc/customizer/customizer.php
This PR introduces the `vanage_import_google_fonts` filter which will allow users to prevent the @import of Google Fonts while still having the font styling being added. This will allow users to manually add the font using an alternative method and prevent Vantage from also importing.
> Add filter to prevent import of Google Font

- css/woocommerce.css
- less/css/woocommerce.less
This PR resolves #300. Currently, the WooCommerce cart and checkout pages don't respect Page Settings. The cart and checkout pages should now respect both page templates and page settings (No Sidebar etc.). Please, also test to ensure that Theme Design > Sidebar is working correctly on these pages. I have and it looks good, Left, Right and None are all working.
> Removed WC cart and checkout specific layouts

- inc/customizer/customizer.php
Resolve #306.
Set the 'description' for each setting inc/customizer.php.
Unlike the setting title, the description isn't automatically escaped (likely due to HTML being expected). @Misplon Are you okay with escaping the description here? I can't see a later instance where we would get to escape this without it affecting other settings. I might have missed a hook so if you know of a later hook, let me know.
The change would be:
`'description' => ! empty( $setting['description'] ) ? $setting['description'] : '',`
To:
`'description' => ! empty( $setting['description'] ) ? esc_html( $setting['description'] ) : '',`
> Customizer: Add ability to set setting description

- inc/customizer/customizer.php
[Reported here](https://siteorigin.com/thread/vantage-theme-typo-in-inc-customizer-customizer-php/)
A user was having trouble overriding SiteOrigin_Customizer_CSS_Builder due to the space in the class_exists check.
> class_exists check for SiteOrigin_Customizer_CSS_Builder typo fix

- inc/template-tags.php
For #308.
`the_custom_logo` outputs the Site Identity logo wrapped in a link. We are already wrapping `vantage_display_logo` in a link. I’d like to remove the link from the header and or menu but don’t want to negatively impact child themes.
This commit also solves the problem of the retina logo not being used if only the Site Identity logo is used for the base logo.
**Logic:**
If Theme Settings > Logo Image is used the Site Identity won’t be displayed even if populated. The Site Identity logo will only be displayed if Theme Settings > Logo Image is empty. If the Retina Logo setting is populated, it’ll function on Retina screens regardless of the base logo in use, either Site Identity or Theme Settings logo.
> Changed the custom logo output function

- inc/customizer.php
@AlexGStapleton Can you give this a quick test. Post categories are using slightly different colors, I've grouped that section with the meta under the post title so we can have two settings added instead of four.
Resolves: https://github.com/siteorigin/vantage/issues/139
> Meta text settings initial commit

- style.css
- style.less
This PR puts the main-navigation just below the WooCommerce gallery which uses a z-index of 1500. There are potential issues with a change of this nature but 9999 is very high once we consider the sticky nav interacting with gallery and lightbox plugins.
> Reduced the main navigation z-index

- inc/customizer.php
- style.css
- style.less
Resolves https://github.com/siteorigin/vantage/issues/327.
@AlexGStapleton The switch to unitless line-height while being broad, should benefit a lot of sites. For example, try changing the sidebar font size to <code>16px</code> and change the body line-height back to <code>1.5em</code>, then test with the body line-height at <code>1.5;</code> and see the difference.
Let me know.
> Sidebar text size setting

- inc/settings.php
- inc/template-tags.php
- single.php
- style.css
- style.less
Resolves https://github.com/siteorigin/vantage/issues/329.
For some reason, when Jetpack Related Posts is activated, the Jetpack Related Posts setting to add the section heading is inverted, when it's off, the heading displays. I'm not quite sure why that is. Otherwise, I think the PR is ready. Let me know if you find anything.
> Added related posts functionality

- inc/template-tags.php
New conditional prevents an error or shortcode outputting when Jetpack account has been disconnected and the related posts module was activated previously when the account was connected.
> Improved the JP related posts conditional

- less/widgets.less
- style.css
- style.less
Main issue I wanted to resolve was the default field height not being enough.
I've left the legacy CSS in place.
> Small input field styling improvements

- less/reset.less
`overflow-y: scroll;` breaks the disable scrolling setting used by lightboxes.
Resolves #349.
For comparison, here is what’s in _s html reset currently https://github.com/Automattic/_s/blob/master/sass/_normalize.scss#L11-L14.
> Removed overflow-y scroll

- inc/extras.php
To view the issue this PR resolves:
1. Make sure the default sidebar widget area is empty.
2. Add a widget to the Shop widget area.
3. View a shop category page, note the widget are under the main content area because `no-sidebar` is being outputted as a body class.
> Replaced is_shop() with is_woocommerce()

- inc/widgets.php
Resole #358. [Related comment](https://github.com/wpengine/phpcompat/issues/275#issuecomment-647154974)
This PR avoids a bug with the PHPCS version [PHP Compatibility Checker](https://en-au.wordpress.org/plugins/php-compatibility-checker/) is using. Basically, it has trouble with inline control structures without braces.
@Misplon I can't seem to get PHP Compatibility Checker to check Vantage quickly enough to avoid a timeout locally so you may need to use a website you have access too to confirm this PR helps.
> PHP Compatibility Checker Fixes

- style.css
- style.less
* Align wide won’t be applied to the boxed layout.
* Align full will be applied to the boxed layout but within the boxed container.
> Apply wide and full styles to full-width layout

- inc/panels.php
This PR resolves an issue that occurs while using the Block Editor. The Legacy Theme Settings code applies even though the meta check passes. This happens due the Block Editor preview and content generation changes not relying on the page id and being block specific. This PR checks for those actions and returns the default `$fields`. An additional post meta check isn't required for those Ajax requests as legacy fields will never be present on a Block Editor powered page.
To test this PR please activate Vantage and then open/create a Block Editor powered page. Add a SiteOrigin Layout Block and add an Archives widget. Open the Row and set a Background Color and Background Image. Wait for the block generation to finish and then save. Reload and open the row. The Background Image won't be …
> Block Editor: Resolve Row Background Saving Issue

- inc/customizer/js/admin.js
- inc/customizer/js/live-customizer.js
This reverts commit 960e3c0f4215b85f54d52b07dab27f83101c5937. Upon further inspection, these are valid uses of the JavaScript [bind()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind) and not jQuery [$.bind()](https://api.jquery.com/bind/);
> Revert "JQuery: Update deprecated .bind() usage"

- inc/customizer/customizer.php
[Related](https://siteorigin.com/thread/debug-log-with-php-8-and-pagebuilder-with-vantage-theme/#comment-586699) 
This PR resolves:
`[29-Jan-2021 17:53:38 UTC] PHP Deprecated: Required parameter $theme follows optional parameter $settings in /var/www/vhosts/DOMAIN/httpdocs/wp-content/themes/vantage/inc/customizer/customizer.php on line 330`
$theme is used in filters so I set the default to generic. $theme is _always_ set so it's unlikely `generic` will ever be used.
> Resolve PHP 8 Deprecated Notice

- inc/customizer/customizer.php
This is required to avoid [a Google performance flag](https://web.dev/font-display/). The value is based on https://github.com/siteorigin/so-widgets-bundle/pull/1072/files
> Google Fonts: Set Font Display

- loops/loop-carousel.php
This PR resolves the following notice:
`Notice: Trying to access array offset on value of type bool in wp-content/themes/test-theme/loops/loop-carousel.php on line 15`
> Resolve Carousel Notice

- inc/customizer/customizer.php
This PR prevents an issue where an invalid font-weight will be used if an italic font is selected. It'll also prevent duplicate font-weight.
> Customizer Fonts: Prevent invalid font property and duplicate

- inc/customizer.php
Resolve https://github.com/siteorigin/vantage/issues/385
`#page-wrapper ` is used instead of .entry-content to allow for the header fonts to be applied to the header and footer.
> Customzier: Use More Specific Selectors for Title and Header Fonts

- functions.php
- js/jquery.theme-main.js
Resolve https://github.com/siteorigin/vantage/issues/389
To test this:
- Install [FitVids for WordPress](https://wordpress.org/plugins/fitvids-for-wordpress/)
- Open js/jquery.theme-main.js and find:
`$( '.entry-content, .entry-content .panel, .entry-video, .woocommerce #main, #masthead-widgets, #header-sidebar' ).fitVids( { ignore: '.tableauViz' } );`
Add the following to the line prior:
`alert( 123 );`
- Disable FitVids in the theme settings (Theme Settings > Layout and untick Use FitVids). Confirm that the alert still happens.
- Apply PR and re-apply the above JS modification.
- Confirm alert doesn't happen, and then re-enable FitVids in theme settings. Confirm alert happens after FitVids is enabled in theme settings.
> Only setup FitVids if Enabled in Theme Settings

- parts/menu.php
Resolve https://github.com/siteorigin/vantage/issues/396
This PR will move the search after the menu. This won't result in any visible differences but it'll ensure the menu is tabbed to before the search.
> Accessibility: Move Search to help with tab order

- inc/customizer.php
- inc/template-tags.php
- style.css
- style.less
The h1 styling is retained to account for a situation where a user previously added a h1 to their header via a widget.
> Change Site Title Tag to p if not front page

- inc/settings.php
Requires https://github.com/siteorigin/settings/pull/77
This PR allows for the for WooCommerce Archives/Shop Page title to be disabled using Page Template Settings.
> Page Template Settings: Allow WC Products and Shop Page Title Override

- inc/settings.php
This issue will restore the Page Featured Image setting. This issue occurred due to the recent settings framework change that resulted in the correct post type being passed rather than just `post` all of the time.
> Page Settings: Correct Post Type Check

- inc/customizer/customizer.php
This PR adds two websafe fonts as possible font choices in the customizer. These two fonts are the two most popular websafe fonts that aren't already included as an option.
> Font Settings: Add Tahoma and Trebucket MS

- inc/widgets.php
[Reported here](https://themes.trac.wordpress.org/ticket/116605#comment:2)
This PR resolve the following notice by the WordPress Theme Check Action:
` "/" (via: home-panels.php) contains PHP errors: Notice: Undefined variable: icon_color in wp-content/themes/vantage/inc/widgets.php on line 75`
This PR can be replicated by adding a Circle Icon widget to a page without setting an icon color - no setting adjustments are required.
> Circle Icon Widget: Resolve Icon Color Notice

- less/widgets.less
- style.css
@AlexGStapleton to recreate this issue:
- Activate Vantage.
- Add a Full Width Stretched Padded row with content. Note the width issue.
- Switch to this branch.
Are you happy with the solution? Let me know if you want to approach this differently, and I'll make adjustments as required.
> Fix Vantage - Page Builder Full Width Stretched Padded Row Display
